package ogrencitakip;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cemre
 */
public class ogrenciEkrani extends javax.swing.JFrame {
    // model olusturuldu
    DefaultTableModel model;
    // sutunlar olusturuldu
    Object[] sutun = {"No","Türkçe1","Mat1","İng1","Sos1","Fen1","Din1","Türkçe2","Mat2","İng2","Sos2","Fen2","Din2"};
    // her satirda bulunacak sutun sayısı kadar obje olusturuldu
    Object[] satir = new Object [13];
    
    DefaultTableModel model2;
    Object[] sutun2 = {"Türkçe","Mat","İng","Sosyal","Fen","Din","Genel Ortalama"};
    Object[] satir2 = new Object [7];
    
    /**
     * Creates new form studentScreen
     */
    // default constructor
    public ogrenciEkrani() {
        initComponents();
    }
    
    // no parametreli constructor
    public ogrenciEkrani(int no){
        initComponents();
        ogrenci.no=no;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Öğrenci Ekranı");

        jPanel1.setBackground(new java.awt.Color(153, 0, 102));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Not Bilgini Gör");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 102)));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ORTALAMALAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // model arayuzdeki table'a baglandi
        this.model = (DefaultTableModel) jTable1.getModel();
        // tablodaki satir sayisi olusturuldu
        this.model.setRowCount(0);
        this.model2 = (DefaultTableModel) jTable2.getModel();
        this.model2.setRowCount(0);
        
        try{
            //System.out.println("tryın içinde,no= "+ ogrenci.no);
            // bir dbHelper objesi oluşturuldu
            DbHelper db = new DbHelper();
            // dbHelperin getConnection metoduyla bir baglanti olusturuldu
            Connection myConn = db.getConnection();
            // veri tabaninda bulunacak verinin stringi yazildi (sorgu)
            String mysqlQuery = "SELECT * FROM notlar WHERE no = '" + ogrenci.no +"'";
            // string PreparedStatement'a donusturuldu
            PreparedStatement preparedStatement = myConn.prepareStatement(mysqlQuery);
            // veri tabanindan sonuc almak icin Result Set olusturuldu
            ResultSet resultSet = preparedStatement.executeQuery();
            // tablolarda bulunacak sutun sayisi girildi
            model.setColumnIdentifiers(sutun);
            model2.setColumnIdentifiers(sutun2);
            
            while (resultSet.next()){
                // tabloda geziliyor
                satir[0] = resultSet.getString("no");
                satir[1] = resultSet.getString("turkce1");
                satir[2] = resultSet.getString("mat1");
                satir[3] = resultSet.getString("ing1");
                satir[4] = resultSet.getString("sosyal1");
                satir[5] = resultSet.getString("fen1");
                satir[6] = resultSet.getString("din1");
                satir[7] = resultSet.getString("turkce2");
                satir[8] = resultSet.getString("mat2");
                satir[9] = resultSet.getString("ing2");
                satir[10] = resultSet.getString("sosyal2");
                satir[11] = resultSet.getString("fen2");
                satir[12] = resultSet.getString("din2");
                
                satir2[0] = notlar.turkceOrtBul(ogrenci.no);
                satir2[1] = notlar.matOrtBul(ogrenci.no);
                satir2[2] = notlar.ingOrtBul(ogrenci.no);
                satir2[3] = notlar.sosOrtBul(ogrenci.no);
                satir2[4] = notlar.fenOrtBul(ogrenci.no);
                satir2[5] = notlar.dinOrtBul(ogrenci.no);
                satir2[6] = notlar.genelOrt(ogrenci.no);
                
                // modele (tablo) satirlar eklendi
                model.addRow(satir);
                model2.addRow(satir2);
                               
            }
            jTable1.setModel(model);
            jTable2.setModel(model2);          
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null,  "Veri tabanı hatası: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ogrenciEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ogrenciEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ogrenciEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ogrenciEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ogrenciEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
